%The data is saved in data.mat at this point
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

load('data.mat');

header = {	'SizeM1',	'SizeM2',	'SizeM3',	'SizeM4',...
    'MeanFlairM1',	'StdFlairM1',	'MeanFlairM2',	'StdFlairM2',...
    'MeanFlairM3',	'StdFlairM3',	'MeanFlairM4',	'StdFlairM4',	...
    'MeanT1M1',	'StdT1M1',	'MeanT1M2',	'StdT1M2',	'MeanT1M3',...
    'StdT1M3',	'MeanT1M4',	'StdT1M4',	'MeanT1cM1',	'StdT1cM1',	...
    'MeanT1cM2',	'StdT1cM2',	'MeanT1cM3',	'StdT1cM3',	'MeanT1cM4',...
    'StdT1cM4',	'MeanT2M1',	'StdT2M1',	'MeanT2M2',	'StdT2M2',...
    'MeanT2M3',	'StdT2M3',	'MeanT2M4',	'StdT2M4'};

medianValuesAndZeros = nanmedian(X);
medianValuesAndZeros(linspace(6,36,16))=0;
[row,col] = find(isnan(X));
X(isnan(X)) = medianValuesAndZeros(col);
